# Generated by Django 5.0.6 on 2024-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals_app', '0002_planet_delete_fruit_delete_vegetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
